# Generated by Django 3.1.3 on 2020-11-20 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=10)),
                ('temperature', models.TextField()),
                ('o2level', models.TextField()),
                ('date', models.TextField()),
                ('address', models.TextField()),
                ('symptoms', models.TextField()),
                ('exitingdisease', models.TextField()),
            ],
        ),
    ]
